# dbt_project.yml 
name: 'manolito_dbt'
version: '1.0.0'
config-version: 2

profile: 'manolito_dbt'

models:
  manolito_dbt: 
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: view
      +schema: gold